### ISSUE TITLE
Document possible targets & architectures

### ISSUE THREAD

**Issue by tversteeg** [calebzulawski/multiversion#21]
It would be nice if the documentation contains a reference or list of possible targets and architectures. Maybe add a URL to: [target_arch](https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch) & [target_feature](https://doc.rust-lang.org/reference/attributes/codegen.html#the-target_feature-attribute)?

Awesome crate by the way!

**Comment by calebzulawski** [comment]
Thanks!  Adding links to the docs is probably the way to go, good idea.

**Comment by calebzulawski** [comment]
I added links to the attributes in 9d8055e7ed04a1bacc60d91627f63c4017906ea7.  Do you think the links are sufficient?
