### ISSUE TITLE
Look into trimming features from regex

### ISSUE THREAD

**Issue by Cocalus** [calebzulawski/multiversion#22]
You should be able to reduce the build time and dependencies a bit, by setting default_features to false for regex according to a conversation in
https://www.reddit.com/r/rust/comments/ghwxml/rust_target_features_performance_pitfall/

**Comment by calebzulawski** [comment]
I think it would actually be very easy to drop the dependency on regex entirely, target specifications should be simple to parse without it.

**Comment by calebzulawski** [comment]
`regex` and `once_cell` are entirely removed by 5b395573b3df3d498e157526bb1a09cb09468dc7.

On my machine this reduces the build in release mode from ~33 to ~22 seconds and `libmultiversion.dylib` from 6.5MB to 5.0MB.
