### ISSUE TITLE
Weird benchmark results when adding multiversion to rawloader

### ISSUE THREAD

**Issue by pedrocr** [calebzulawski/multiversion#24]
Thanks for creating this. I've been hoping for something like this for a while now. I'm the author of rawloader:

https://github.com/pedrocr/rawloader/

The raw file decoders have a bunch of hot loops that I know can be sped up with new processor features from compiling with `target-cpu=native`. I've been doing some performance work in rawloader and have a stable benchmark I can use for any file. I tried adding multiversion to the NEF format used by Nikon cameras and saw these numbers for the average decode time:

Version | Time (in ms)
-- | --
Master | 322.9
Master with `target-cpu=native` | 300.4 (-7%)
Master with only multiversion dependency | 310.9 (-4%)
Master with `[x86\|x86_64]+avx` annotation in NEF | 317.3 (-2%)
Master with `x86_64+avx+avx2+bmi1+bmi2+fma+lzcnt+xsave` annotation in NEF | 283.9 (-12%)

So, initially I wasn't able to replicate the `target-cpu=native` result, probably because I needed to enable more features. But what is odd is that just adding `multiversion` as a dependency speeds things up and then actually adding versioning makes things slower. Finally I did a target with most features the CPU should have and got a result that was significantly better than `target-cpu=native` which shouldn't be possible at all.

Any ideas on what could be happening here? Maybe it's just the binaries being particularly sensitive to memory layout but I'm also wondering what else multiversion could be doing here.

**Comment by calebzulawski** [comment]
I'm guessing it either has something to do with memory layout, or just an inconsistent benchmark.  I wouldn't expect enabling AVX to do much, after looking at the code, since it looks like integer math and AVX mostly adds floating point instructions.  It is somewhat odd that using multiversion is faster than `target-cpu=native`, and that may also be due to an inconsistent benchmark.  Simply adding a dependency on multiversion may not even change the layout (since it's unused).  I think it's possible CPU or disk cache is playing a role in the faster runs.

**Comment by pedrocr** [comment]
I'll do more benchmarks to try and be sure but it seems quite stable. I've since tested other formats and it seems more reasonable in those cases.

**Comment by pedrocr** [comment]
This is most likely from alignment issues. I played around with some `#[repr(align(N))]` declarations in the key struct and there's a sweet spot at 32 that creates almost the same speedup as just adding the new dependency. So the new dependency is probably changing the layout enough for this to happen and it's nothing more complex.

The difference between `target-cpu=native` and enabling all the features may also be alignment stuff helping with vectorization. Or it may be that enabling the features but not the the target CPU is changing the LLVM code generation in ways that happen to be beneficial to this code.

Having seen the macro expansion these explanations all seem fair so I'll close this now.
