### ISSUE TITLE
Failed compilation with a multiversion/clone annotation

### ISSUE THREAD

**Issue by pedrocr** [calebzulawski/multiversion#26]
I've been trying out multiversion in several raw formats and for some reason in ARW the same annotation that works in other places fails to compile with this error:

```
$ cargo build --release
   Compiling rawloader v0.36.3 (/home/pedrocr/data/core/Projects/rawloader)
error[E0425]: cannot find function `decode_arw2_avx_avx2_bmi1_bmi2_fma_lzcnt_xsave_version` in this scope
   --> src/decoders/arw.rs:202:17
    |
202 |   pub(crate) fn decode_arw2(buf: &[u8], width: usize, height: usize, curve: &LookupTable, dummy: bool) -> Vec<u16> {
    |                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `__safe_inner_decode_arw2_avx_avx2_bmi1_bmi2_fma_lzcnt_xsave_version` in this scope
   --> src/decoders/arw.rs:200:3
    |
200 |   #[multiversion]
    |   ^^^^^^^^^^^^^^^ not found in this scope
    |
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find value `__decode_arw2_avx_avx2_bmi1_bmi2_fma_lzcnt_xsave_static_dispatch` in this scope
   --> src/decoders/arw.rs:202:17
    |
202 |   pub(crate) fn decode_arw2(buf: &[u8], width: usize, height: usize, curve: &LookupTable, dummy: bool) -> Vec<u16> {
    |                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `decode_arw2_default_version` in this scope
   --> src/decoders/arw.rs:202:17
    |
202 |   pub(crate) fn decode_arw2(buf: &[u8], width: usize, height: usize, curve: &LookupTable, dummy: bool) -> Vec<u16> {
    |                 ^^^^^^^^^^^ not found in this scope

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `rawloader`.

To learn more, run the command again with --verbose.
```

I'm annotating the function like the others with the following code:

```rust
  #[multiversion]
  #[clone(target = "x86_64+avx+avx2+bmi1+bmi2+fma+lzcnt+xsave")]
  pub(crate) fn decode_arw2(buf: &[u8], width: usize, height: usize, curve: &LookupTable, dummy: bool) -> Vec<u16> {
```

**Comment by calebzulawski** [comment]
This is odd and I'm suspecting it's a bug.  Is there anything notably different about the arw2 function vs the other formats?  It may be helpful to debug this with `cargo-expand` or similar.

**Comment by pedrocr** [comment]
The NEF function seems equally complex:

```rust
  #[multiversion]
  #[clone(target = "x86_64+avx+avx2+bmi1+bmi2+fma+lzcnt+xsave")]
  pub(crate) fn do_decode(src: &[u8], meta: &[u8], endian: Endian, width: usize, height: usize, bps: usize, dummy: bool) -> Result<Vec<u16>, String> {
```

In the same file the ARW1 format also fails and that even has a simpler signature:

```rust
  #[multiversion]
  #[clone(target = "x86_64+avx+avx2+bmi1+bmi2+fma+lzcnt+xsave")]
  pub(crate) fn decode_arw1(buf: &[u8], width: usize, height: usize, dummy: bool) -> Vec<u16> {
```

At a guess maybe something about the rest of the file is being wrongly parsed. I'm compiling `cargo-expand` to have a look.

**Comment by pedrocr** [comment]
Here's the expanded version:

https://gist.github.com/pedrocr/317599244c8822fd9e4af54e7882db57

Maybe a missing `pub (crate)` in the definition of `__safe_inner_decode_arw1_avx_avx2_bmi1_bmi2_fma_lzcnt_xsave_version`?

**Comment by calebzulawski** [comment]
Ah, I figured it out after reading it over again.  The problem is that `decode_arw1` is an associated function that doesn't take a `self` parameter--unfortunately there is no way for multiversion to determine that this is an associated function and use the appropriate function call.  A workaround would be to multiversion a non-associated function and call that from the associated function.  I have thought about adding an `#[associated_fn]` attribute to hint this, or possibly require marking the entire `impl` block with `#[multiversion]`.

**Comment by pedrocr** [comment]
But that's also true of the NEF case. Why does it work in that situation?

**Comment by calebzulawski** [comment]
Hmm.  There's no obvious reason it should work if it's an associated function.

**Comment by pedrocr** [comment]
Here's the expanded NEF decoder that compiles fine:

https://gist.github.com/pedrocr/110bce624d2cf09c2f1c0f498c51cd79

**Comment by calebzulawski** [comment]
Took me a while but I figured it out.  The one that compiles fine uses the `Self` token, which is only valid in associated functions and the macro uses it as a hint.  This is frankly just too confusing, so I think in the next version of multiversion I may just require something like this:

```
#[multiversion_impl]
impl Foo {
    #[multiversion]
    fn foo() {}
}
```

**Comment by pedrocr** [comment]
I had noticed that difference too. But swapping it doesn't change anything. NEF still compiles fine if I do `NefDecoder::do_decode` and ARW still doesn't compile if I do `Self::decode_arw1`.

**Comment by pedrocr** [comment]
But you're right that in the expanded code one uses `Self::` and the other doesn't. But it's strange that the macro knows how to do this for one case but not the other. Both cases follow the same structure as far as I can tell.

**Comment by pedrocr** [comment]
Found the difference:

- NEF goes inside the same `impl<'a> NefDecoder<'a>` first through `decode_compressed(&self)` and only then to `Self::do_decode`
- ARW goes straight to `Self::decode_arw2` from a different context. Apparently that's enough to throw off the macro even though the actual function being annotated is the same. Strange that that would happen.

**Comment by calebzulawski** [comment]
I cleaned up this behavior a bit in 16c3aa1baf1a56c743e7e9b65a2cfcad0cf4feb9.

There is now a configuration `associated_fn` that can be set to `true` or `false`.  The logic for determining the default value is simpler, too.  If the function's first argument is some form of `self`, it's set to `true`, otherwise `false`.
