### ISSUE TITLE
There should be some way to specify associated constants for different architectures

### ISSUE THREAD

**Issue by Sp00ph** [calebzulawski/multiversion#36]
Currently, there's no facility in `std::simd` that allows you to choose the largest vector type with hardware support. It would be handy to be able to make a function `foo<const N: usize>()` which uses vectors of length `N` internally and then vary the value for `N` at the callsite depending on the hardware. One could e.g. imagine a `is_ascii<const N: usize>()` which checks blocks of `N` bytes at once and which would use 16-byte vectors on SSE2, 32 byte vectors on AVX2 or 64 byte vectors on AVX512.

Allowing you to associate any constant with the different instantiations would be a more general solution, though for this specific case it might already be enough to expose a single constant like `HARDWARE_VECTOR_SIZE`.

**Comment by calebzulawski** [comment]
Is [suggested_simd_width](https://docs.rs/target-features/0.1.3/target_features/struct.Target.html#method.suggested_simd_width), provided by the [selected_target!](https://docs.rs/multiversion/0.7.2/multiversion/target/macro.selected_target.html) macro what you're looking for?

**Comment by Sp00ph** [comment]
It is, I guess I just didn't know where to look in the docs. Thanks!
