### ISSUE TITLE
[Help]When should #[multiversion(targets = "simd")] be used

### ISSUE THREAD

**Issue by yyy33** [calebzulawski/multiversion#41]
Hi, I'm writing a crate,and I'm hoping that it might utilize `simd` acceleration. There is a mention in [simd-book](https://calebzulawski.github.io/rust-simd-book/2-portable-simd.html) that auto-vectorization is only effective in certain situations. So how should I make sure that the method I'm writing can be autovectorized using `#[multiversion(targets = "simd")]` or do I need to use `std::simd` or `std::arch `to vectorize manually when the method doesn't support autovectorizing

**Comment by calebzulawski** [comment]
`targets = "simd"` is a just shortcut for listing all of the SIMD target features for every platform--it doesn't do anything special to ensure vectorization.  You can check the assembly of your program to ensure that it is being vectorized, or you can use `std::simd` or `std::arch`.

**Comment by yyy33** [comment]
> `targets = "simd"` is a just shortcut for listing all of the SIMD target features for every platform--it doesn't do anything special to ensure vectorization. You can check the assembly of your program to ensure that it is being vectorized, or you can use `std::simd` or `std::arch`.

Thanks for your reply, it was very helpful!
