### ISSUE TITLE
Warning with Rust 1.80: unexpected `cfg` condition name: `target`

### ISSUE THREAD

**Issue by hniksic** [calebzulawski/multiversion#43]
Beginning with Rust 1.80 our usages of `target_cfg_f!` result in warnings about unexpected `cfg` condition name `target`. For example, this code:

```rust
#[multiversion(targets("x86_64+sse4.1"))]
fn parse_naive_datetime(input: &[u8], time_date_separator: u8) -> Option<NaiveDateTime> {
    #[cfg(target_arch = "x86_64")]
    unsafe {
        if target_cfg_f!(target = "x86_64+sse4.1") {
            return parse_naive_datetime_sse4_1(input, time_date_separator);
        }
    }
    parse_naive_datetime_fallback(input, time_date_separator)
}
```

emits the following warning:

```
warning: unexpected `cfg` condition name: `target`
   --> driver_framework/src/serde/datetime.rs:175:26
    |
175 |         if target_cfg_f!(target = "x86_64+sse4.1") {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a Cargo feature instead
    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
             [lints.rust]
             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target, values("x86_64+sse4.1"))'] }
    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(target, values(\"x86_64+sse4.1\"))");` to the top of the `build.rs`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
```

Is this an issue with `multiversion`, or are we using it incorrectly? The current formulation was arrived at [here](https://github.com/calebzulawski/multiversion/issues/38). Any help or pointer would be appreciated.

**Comment by calebzulawski** [comment]
`target` is not a variable recognized by `cfg`, so you should be using something like `target_cfg_f!(all(target_arch = "x86_64", target_feature = "sse4.1"))`.

Rust just added `cfg` validation which fortunately catches errors like this, which is why you are suddenly seeing this

**Comment by hniksic** [comment]
@calebzulawski Thanks! This indicates that we've been using the fallback code since the upgrade to 0.7.

There is also code that attempts to request multiple features, e.g. `target_cfg_f!(target = "x86_64+avx2+pclmulqdq")`. Can that be changed to `target_cfg_f!(all(target_arch = "x86_64", target_feature = "avx2", target_feature = "pclmulqdq"))`?

**Comment by calebzulawski** [comment]
Yep! Exactly that.

**Comment by hniksic** [comment]
Thanks for the help, closing this one.
